export enum StorageKey {
  usuario = 'usuario',
  geolocalizacion = 'geolocalizacion',
  preferenciasCliente = 'preferenciasCliente',
  ruta = 'ruta',
  queryParams = 'queryParams',
  menuCollapsed = 'menuCollapsed',
  carroCompraB2B = 'carroCompraB2B',
  ov = 'ov',
  gclid = 'gclid',
  fbclid = 'fbclid',
  invitado = 'invitado',
  recibe = 'recibe',
  fechas = 'fechas',
  Metodo = 'Metodo',
  monto = 'monto',
  folio = 'folio',
  ordenCompraCargada = 'ordenCompraCargada',
  tiendaRetiro = 'tiendaRetiro',
  catalogo = 'catalogo',
  tags = 'tags',
  buscadorB2B = 'buscadorB2B',
  bannersMarca = 'bannersMarca',
  favoritos = 'favoritos',
  wishlistItems = 'wishlistItems',
  utm_campaign = 'utm_campaign',
}
